title: cripto.cat
default_lang: ca
author:
  name: 'Hermes Diactoros'
  email: diactoros@protonmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Per una vida digital lliure i anònima'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
